"""08: Gini, alias merging, review rounds and the AI-signal patterns."""
import pytest


@pytest.fixture
def m(scripts):
    return scripts("08_process_metrics.py")


def test_gini(m):
    assert m.gini([5, 5, 5, 5]) == 0
    assert m.gini([0, 0, 0, 10]) == pytest.approx(0.75)
    assert m.gini([]) == 0


def test_aliases_join_through_email_name_and_login(m):
    p = m.People()
    p.add("Jane Doe", "jane@school.ca")
    p.add("jdoe", "12345+JDoe@users.noreply.github.com")  # login from the noreply address
    p.add("Jane D", "jane@school.ca", "jdoe")             # the API links email and login
    p.add("jane doe", "other@gmail.com")                  # same normalised name
    ids = {p.find("e:jane@school.ca"), p.of_login("JDoe"), p.find("e:other@gmail.com")}
    assert len(ids) == 1
    assert p.of_login("someone-else") not in ids


def review(login, when):
    return {"author": {"login": login}, "state": "COMMENTED", "submittedAt": when,
            "comments": {"totalCount": 0}}


def commit(when):
    return {"commit": {"authoredDate": when}}


def test_review_rounds_count_reviews_followed_by_commits(m):
    pr = {"reviews": {"nodes": [review("amy", "2025-01-01T10:00:00Z"),
                                review("bob", "2025-01-02T10:00:00Z"),
                                review("author", "2025-01-01T11:00:00Z")]},
          "commits": {"nodes": [commit("2025-01-01T09:00:00Z"), commit("2025-01-01T12:00:00Z")]}}
    # amy's review was followed by a commit, bob's was not, the author's own one is ignored
    assert m.review_rounds(pr, "author") == 2
    pr["reviews"]["nodes"] = [review("author", "2025-01-01T11:00:00Z")]
    assert m.review_rounds(pr, "author") is None


@pytest.mark.parametrize("message, expected", [
    ("Add login\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)", True),
    ("Fix parser\n\nWritten with GitHub Copilot", True),
    ("feat(tui): add preview\n\nScrollable view of the resume generated by Codex.", False),
    ("Voice chat implemented using OpenAI GPT 4o Realtime", False),
])
def test_explicit_attribution_needs_a_statement_about_the_code(m, message, expected):
    assert bool(m.EXPLICIT.search(message)) is expected


def test_agents_and_bots(m):
    assert m.is_agent("copilot-swe-agent[bot]", "198982749+Copilot@users.noreply.github.com")
    assert m.is_agent("Cursor Agent", "cursoragent@cursor.com")
    assert not m.is_agent("Devin", "devhze@yahoo.com")
    assert not m.is_agent("Claudia Smith", "claudia@school.ca")
    assert m.is_agent("", "", "copilot-pull-request-reviewer")
    assert m.is_bot("", "", "github-classroom")
    assert m.is_bot("dependabot[bot]", "49699333+dependabot[bot]@users.noreply.github.com")
