"""Team process metrics and AI-usage signals for every selected repo.

Inputs: the clones in data/repos (with PR heads under refs/pull/, from 02_clone.sh) and
the GitHub API data in data/github (from 07_github_api.py).
Outputs (aggregates only, no names or logins):
    results/process_metrics.csv   repository evolution, review process, collaboration,
                                  development velocity (one row per repo)
    results/ai_signals.csv        AI-assisted development signals (one row per repo)

Definitions are in docs/process_metrics.md.
"""
import argparse
import json
import re
import statistics
from collections import defaultdict
from datetime import datetime, timezone

import pandas as pd

from common import RESULTS, ROOT, git, read_selection, repo_dir, select

GITHUB = ROOT / "data" / "github"

BOT = re.compile(r"\[bot\]|dependabot|github-actions|github-classroom|actions-user|renovate", re.I)
# AI coding agents that commit or open PRs under their own account
AGENT = re.compile(r"copilot-swe-agent|^copilot$|\+copilot@users\.noreply|cursoragent@|"
                   r"^cursor agent$|^claude$|noreply@anthropic\.com|^codex$|chatgpt-codex", re.I)
# AI code reviewers; GraphQL returns bot logins without the [bot] suffix
AI_REVIEWER = re.compile(r"copilot-pull-request-reviewer|coderabbit|gemini-code-assist|sourcery-ai|"
                         r"cursor\[?bot|chatgpt-codex-connector|claude", re.I)
TOOL = r"(copilot|claude|codex|cursor|openai|chatgpt|gemini)"
COAUTHOR = re.compile(r"^\s*co-authored-by:\s*(.+)$", re.I | re.M)
# an author stating that code was produced with a named tool, e.g. "Generated with
# [Claude Code]"; anchored to the start of a line so product descriptions such as
# "resume generated by Codex" in the middle of a sentence do not match
EXPLICIT = re.compile(r"^\W*(generated|written|created|fixed|implemented|refactored|assisted|"
                      r"co-written|authored)\s+(with|by|using)\s+(the help of\s+)?\[?"
                      r"(github\s+)?" + TOOL, re.I | re.M)
AI_BRANCH = re.compile(r"^(copilot|codex|claude|cursor)/", re.I)
AGENT_FILES = re.compile(r"(^|/)(AGENTS\.md|CLAUDE\.md|GEMINI\.md|\.cursorrules|"
                         r"copilot-instructions\.md|\.cursor/rules/)", re.I)
LLM_FEATURE = re.compile(r"\b(llms?|gpt|openai|gemini|ollama|anthropic|langchain|"
                         r"language models?)\b", re.I)
PREFIX = re.compile(r"^(feature|feat|fix|bugfix|hotfix|bug|refactor|chore|docs?|tests?|"
                    r"release)[/_-]", re.I)
DEV_BRANCH = re.compile(r"^(dev|develop|development)$", re.I)
HOUR, DAY, WEEK = 3600, 86400, 7 * 86400


def ts(iso):
    return datetime.fromisoformat(iso.replace("Z", "+00:00")).timestamp() if iso else None


def gini(values):
    """Gini coefficient of non-negative values (0 = perfectly even)."""
    x = sorted(values)
    n, total = len(x), sum(x)
    if n == 0 or total == 0:
        return 0.0
    return sum((2 * i - n + 1) * v for i, v in enumerate(x)) / (n * total)


def pct(part, whole):
    return 100 * part / whole if whole else None


def median(xs):
    return statistics.median(xs) if xs else None


def quantile(xs, q):
    return float(pd.Series(xs).quantile(q)) if xs else None


def norm_name(name):
    return re.sub(r"[^a-z0-9]", "", name.lower())


def noreply_login(email):
    m = re.match(r"(?:\d+\+)?([^@]+)@users\.noreply\.github\.com$", email)
    return m.group(1).lower() if m else None


class People:
    """Union-find over author names, emails and GitHub logins: two identities are one
    person if they share a normalised name, an email address or a login."""

    def __init__(self):
        self.parent = {}

    def find(self, k):
        self.parent.setdefault(k, k)
        while self.parent[k] != k:
            self.parent[k] = self.parent[self.parent[k]]
            k = self.parent[k]
        return k

    def union(self, *keys):
        keys = [k for k in keys if k and not k.endswith(":")]
        for k in keys[1:]:
            self.parent[self.find(k)] = self.find(keys[0])

    def add(self, name="", email="", login=""):
        email = (email or "").lower()
        login = (login or noreply_login(email) or "").lower()
        self.union("n:" + norm_name(name or ""), "e:" + email, "l:" + login)

    def of_commit(self, c):
        return self.find("e:" + c["email"]) if c["email"] else self.find("n:" + norm_name(c["name"]))

    def of_login(self, login):
        return self.find("l:" + login.lower())


def is_bot(name, email, login=""):
    return bool(BOT.search(f"{name} {email} {login}"))


def is_agent(name, email, login=""):
    return any(AGENT.search(s) for s in (name, email, login) if s) or bool(login and AI_REVIEWER.search(login))


def read_commits(path):
    """Every commit reachable from any branch or PR head."""
    out = git(path, "log", "--all", "--format=%x1d%H%x1f%P%x1f%an%x1f%ae%x1f%at%x1f%B")
    commits = []
    for rec in out.split("\x1d")[1:]:
        parts = rec.split("\x1f", 5)
        if len(parts) < 6:
            continue
        h, parents, name, email, at, body = parts
        commits.append({"sha": h, "merge": len(parents.split()) > 1, "name": name,
                        "email": email.lower(), "at": int(at), "body": body})
    return commits


def branches(path):
    refs = git(path, "for-each-ref", "--format=%(refname:lstrip=3)", "refs/remotes/origin")
    return [b for b in refs.splitlines() if b and b != "HEAD"]


def evolution(team, merges, heads, pid):
    t0, t1 = min(c["at"] for c in team), max(c["at"] for c in team)
    span_days = max((t1 - t0) / DAY, 1)
    weeks = {(c["at"] - t0) // WEEK for c in team}
    by_person = defaultdict(list)
    for c in team:
        by_person[pid(c)].append(c)
    counts = [len(v) for v in by_person.values()]
    days = [len({datetime.fromtimestamp(c["at"], timezone.utc).date() for c in v})
            for v in by_person.values()]
    n = len(team)
    return {
        "evo_team_commits": n,
        "evo_span_days": round(span_days),
        "evo_commits_per_day": n / span_days,
        "evo_commits_per_week": n / span_days * 7,
        "evo_weeks_active_pct": pct(len(weeks), int(span_days // 7) + 1),
        "evo_authors": len(by_person),
        "evo_median_commits_per_author": median(counts),
        "evo_median_active_days_per_author": median(days),
        "evo_branches": len(heads),
        "evo_prefixed_branches_pct": pct(sum(bool(PREFIX.match(b)) for b in heads), len(heads)),
        "evo_has_dev_branch": any(DEV_BRANCH.match(b) for b in heads),
        "evo_merge_commits_pct": pct(len(merges), len(merges) + n),
        "col_contributors": len(by_person),
        "col_core_contributors": sum(1 for k in counts if k / n >= 0.05),
        "col_top_author_share_pct": pct(max(counts), n),
        "col_smallest_author_share_pct": pct(min(counts), n),
        "col_gini": gini(counts),
    }, span_days


def review_rounds(pr, author_login):
    """1 + the number of reviews by someone other than the author that were followed by
    at least one further commit on the PR. None for a PR nobody else reviewed."""
    reviews = [r for r in pr["reviews"]["nodes"]
               if r["author"] and r["author"]["login"].lower() != author_login and r["submittedAt"]]
    if not reviews:
        return None
    commit_times = [ts(c["commit"]["authoredDate"]) for c in pr["commits"]["nodes"]]
    return 1 + sum(1 for r in reviews if any(t > ts(r["submittedAt"]) for t in commit_times))


def review_process(prs, issues, span_days, people, snap_t):
    humans = [p for p in prs if p["author"] and not is_bot("", "", p["author"]["login"])
              and not is_agent("", "", p["author"]["login"])]
    merged = [p for p in humans if p["mergedAt"] and ts(p["mergedAt"]) <= snap_t]
    first_review_h, rounds, comments, reviewed, approved, merged_by_other = [], [], [], 0, 0, 0
    pair_set, reviews_by, authors_per_pr = set(), defaultdict(int), []
    pr_authors = {people.of_login(p["author"]["login"]) for p in humans}
    for p in humans:
        a = p["author"]["login"].lower()
        others = [r for r in p["reviews"]["nodes"]
                  if r["author"] and r["author"]["login"].lower() != a and r["submittedAt"]
                  and not is_bot("", "", r["author"]["login"]) and not is_agent("", "", r["author"]["login"])]
        comments.append(p["comments"]["totalCount"]
                        + sum(r["comments"]["totalCount"] for r in p["reviews"]["nodes"]))
        if others:
            first_review_h.append((min(ts(r["submittedAt"]) for r in others) - ts(p["createdAt"])) / HOUR)
            rounds.append(review_rounds(p, a))
        for r in others:
            reviewer = people.of_login(r["author"]["login"])
            reviews_by[reviewer] += 1
            if reviewer in pr_authors and reviewer != people.of_login(a):
                pair_set.add((reviewer, people.of_login(a)))
        who = set()
        for c in p["commits"]["nodes"]:
            au = c["commit"]["author"] or {}
            login = (au.get("user") or {}).get("login", "")
            if is_bot(au.get("name", ""), au.get("email", ""), login) or \
                    is_agent(au.get("name", ""), au.get("email", ""), login):
                continue
            who.add(people.of_login(login) if login else
                    people.find("e:" + (au.get("email") or "").lower()))
        if who:
            authors_per_pr.append(len(who))
    for p in merged:
        a = p["author"]["login"].lower()
        states = {r["state"] for r in p["reviews"]["nodes"]
                  if r["author"] and r["author"]["login"].lower() != a}
        reviewed += bool(states)
        approved += "APPROVED" in states
        merged_by_other += bool(p["mergedBy"]) and p["mergedBy"]["login"].lower() != a
    ttm = [(ts(p["mergedAt"]) - ts(p["createdAt"])) / HOUR for p in merged]
    sizes = [p["additions"] + p["deletions"] for p in merged]
    files = [p["changedFiles"] for p in merged]
    commits = [p["commits"]["totalCount"] for p in merged]
    n_dev = len(pr_authors)
    team_reviews = sum(v for k, v in reviews_by.items() if k in pr_authors)

    closed = [i for i in issues if i["closedAt"] and ts(i["closedAt"]) <= snap_t]
    close_days = [(ts(i["closedAt"]) - ts(i["createdAt"])) / DAY for i in closed]
    return {
        "rev_prs": len(humans),
        "rev_merged_pct": pct(len(merged), len(humans)),
        "rev_prs_per_week": len(humans) / span_days * 7,
        "rev_pr_size_median": median(sizes),
        "rev_pr_files_median": median(files),
        "rev_commits_per_pr_median": median(commits),
        "rev_commits_per_pr_mean": statistics.mean(commits) if commits else None,
        "rev_reviewed_pct": pct(reviewed, len(merged)),
        "rev_approved_pct": pct(approved, len(merged)),
        "rev_merged_by_other_pct": pct(merged_by_other, len(merged)),
        "rev_first_review_h_median": median(first_review_h),
        "rev_rounds_mean": statistics.mean(rounds) if rounds else None,
        "rev_comments_per_pr_mean": statistics.mean(comments) if comments else None,
        "rev_comments_per_pr_median": median(comments),
        "rev_uncommented_pct": pct(sum(k == 0 for k in comments), len(comments)),
        "rev_reviews_per_dev": team_reviews / n_dev if n_dev else None,
        "col_pr_authors": n_dev,
        "col_authors_per_pr": statistics.mean(authors_per_pr) if authors_per_pr else None,
        "col_multi_author_pr_pct": pct(sum(k > 1 for k in authors_per_pr), len(authors_per_pr)),
        "col_review_pairs": len(pair_set),
        "col_network_density": len(pair_set) / (n_dev * (n_dev - 1)) if n_dev > 1 else None,
        "vel_merged_prs": len(merged),
        "vel_ttm_median_h": median(ttm),
        "vel_ttm_p75_h": quantile(ttm, 0.75),
        "vel_merged_24h_pct": pct(sum(t <= 24 for t in ttm), len(ttm)),
        "vel_issues": len(issues),
        "vel_issues_closed_pct": pct(len(closed), len(issues)),
        "vel_issue_close_median_days": median(close_days),
        "vel_issue_close_p75_days": quantile(close_days, 0.75),
    }


def ai_signals(window, heads, prs, snapshot_files):
    coauthor, agent, explicit, tools = set(), set(), set(), defaultdict(int)
    for c in window:
        for line in COAUTHOR.findall(c["body"]):
            m = re.search(TOOL, line, re.I)
            if m:
                coauthor.add(c["sha"])
                tools[m.group(1).lower()] += 1
        if is_agent(c["name"], c["email"]):
            agent.add(c["sha"])
        body = COAUTHOR.sub("", c["body"])
        if EXPLICIT.search(body):
            explicit.add(c["sha"])
    ai_branches = {b for b in heads if AI_BRANCH.match(b)}
    ai_branches |= {p["headRefName"] for p in prs if p["mergedAt"] and AI_BRANCH.match(p["headRefName"])}
    config = sorted({f.split("/")[-1] for f in snapshot_files if AGENT_FILES.search(f)})
    ai_reviews = sum(1 for p in prs for r in p["reviews"]["nodes"]
                     if r["author"] and AI_REVIEWER.search(r["author"]["login"]))
    ai = coauthor | agent | explicit
    nonmerge = [c for c in window if not c["merge"]]
    llm = sum(1 for c in nonmerge if c["sha"] not in ai and LLM_FEATURE.search(c["body"]))
    return {
        "ai_coauthor_commits": len(coauthor),
        "ai_coauthor_claude": tools["claude"], "ai_coauthor_copilot": tools["copilot"],
        "ai_coauthor_cursor": tools["cursor"],
        "ai_coauthor_other": sum(v for k, v in tools.items() if k not in ("claude", "copilot", "cursor")),
        "ai_agent_commits": len(agent),
        "ai_branches": len(ai_branches),
        "ai_explicit_commits": len(explicit),
        "ai_config_files": ";".join(config),
        "ai_reviews": ai_reviews,
        "ai_traced_commits": len(ai),
        "ai_traced_pct": pct(len(ai), len(window)),
        "ai_any_signal": bool(ai or ai_branches or config or ai_reviews),
        "ai_llm_feature_commits": llm,
    }


def measure(org, repo, year, inv, res):
    path = repo_dir(year, repo)
    snap = res.loc[repo, "commit_sha"]
    created = ts(inv.loc[repo, "created_at"])
    snap_t = int(git(path, "show", "-s", "--format=%ct", snap))
    commits = read_commits(path)
    window = [c for c in commits if created <= c["at"] <= snap_t]
    heads = branches(path)

    gh = GITHUB / str(year) / repo
    prs = [p for p in json.loads((gh / "prs.json").read_text())
           if created <= ts(p["createdAt"]) <= snap_t]
    issues = [i for i in json.loads((gh / "issues.json").read_text())
              if created <= ts(i["createdAt"]) <= snap_t
              and not (i["author"] and is_bot("", "", i["author"]["login"]))]

    people = People()
    for c in window:
        people.add(c["name"], c["email"])
    for p in prs:  # the API links commit emails to GitHub logins
        for c in p["commits"]["nodes"]:
            au = c["commit"]["author"] or {}
            people.add(au.get("name", ""), au.get("email", ""), (au.get("user") or {}).get("login", ""))

    human = [c for c in window if not is_bot(c["name"], c["email"]) and not is_agent(c["name"], c["email"])]
    team = [c for c in human if not c["merge"]]
    merges = [c for c in window if c["merge"]]
    row = {"cohort_year": year, "org": org, "repo": repo, "commit_sha": snap}
    evo, span_days = evolution(team, merges, heads, people.of_commit)
    row.update(evo)
    row.update(review_process(prs, issues, span_days, people, snap_t))
    ai = {"cohort_year": year, "org": org, "repo": repo, "ai_window_commits": len(window)}
    ai.update(ai_signals(window, heads, prs, git(path, "ls-tree", "-r", "--name-only", snap).splitlines()))
    return row, ai


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", help="one repo (name or org/repo); prints instead of writing")
    args = ap.parse_args()
    inv = pd.read_csv(RESULTS / "repo_inventory.csv").set_index("repo")
    res = pd.read_csv(RESULTS / "results.csv").set_index("repo")
    items = read_selection()
    if args.only:
        items = select(items, args.only)
    rows, ai = [], []
    for org, repo, year in items:
        r, a = measure(org, repo, year, inv, res)
        rows.append(r)
        ai.append(a)
    proc, sig = pd.DataFrame(rows), pd.DataFrame(ai)
    if args.only:
        print(proc.T.to_string(), sig.T.to_string(), sep="\n")
        return
    proc.round(4).to_csv(RESULTS / "process_metrics.csv", index=False)
    sig.round(4).to_csv(RESULTS / "ai_signals.csv", index=False)
    print(f"wrote results/process_metrics.csv and results/ai_signals.csv ({len(proc)} repos)")


if __name__ == "__main__":
    main()
